# Generated by Django 4.0.5 on 2022-06-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
